<?php return array (
  'telegramtoken' => '6383320230:AAFwIO_KRXTuurMNq4sXU5SYPwIGHLPwFx0',
  'telegramid' => '-987314401',
  'dashboardform' => '',
  'provincefield' => 'cProvince',
  'districtfield' => 'cDistrict',
  'communefield' => 'cCommune',
  'metabaseurl' => 'https://metabase.analyticalx.org',
  'metabasesecret' => '551d9823395196dd2dc6d495a18f7d1f45e66ecf45b5defebf9ec12c8c54f52b',
  'metabasedashboard' => '4',
  'metabasequestion' => '',
  'phpmyadmin' => '',
  'storagedisk' => 'public',
  'storagepath' => 'dcxresea_dcxdpa',
  'backgroundimage' => '',
  'partnerimage' => '',
  'disclaimer' => '',
);